package tui

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/manutej/maat-terminal/internal/graph"
)

// GetMockGraph returns realistic mock nodes and edges for testing the TUI.
// Following Commandment #1 (Immutable Truth): Pure function, deterministic output.
func GetMockGraph() ([]graph.Node, []graph.Edge) {
	now := time.Now()

	nodes := []graph.Node{
		// Projects (5)
		{
			ID:     "project:maat",
			Type:   graph.NodeTypeProject,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"name":        "MAAT",
				"description": "Terminal knowledge graph workspace",
				"status":      "active",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, -3, 0),
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now,
			},
		},
		{
			ID:     "project:frontend",
			Type:   graph.NodeTypeProject,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"name":        "Frontend",
				"description": "UI and interaction layer",
				"status":      "active",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, -2, 0),
				UpdatedAt:   now.AddDate(0, 0, -5),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -5),
			},
		},
		{
			ID:     "project:backend",
			Type:   graph.NodeTypeProject,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"name":        "Backend",
				"description": "API and graph storage",
				"status":      "active",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, -2, 0),
				UpdatedAt:   now.AddDate(0, 0, -3),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -3),
			},
		},
		{
			ID:     "project:infra",
			Type:   graph.NodeTypeProject,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"name":        "Infrastructure",
				"description": "DevOps and deployment",
				"status":      "planning",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, -1, 0),
				UpdatedAt:   now.AddDate(0, 0, -7),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -7),
			},
		},
		{
			ID:     "project:design",
			Type:   graph.NodeTypeProject,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"name":        "Design System",
				"description": "UI components and patterns",
				"status":      "active",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, -1, -15),
				UpdatedAt:   now.AddDate(0, 0, -2),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -2),
			},
		},

		// Issues (20) - mix of statuses, priorities, and labels
		{
			ID:     "issue:1",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Implement graph rendering engine",
				"description": "Create hierarchical tree layout for knowledge graph visualization",
				"status":      "in_progress",
				"priority":    2,
				"labels":      []string{"enhancement", "ui", "p1"},
				"assignee":    "dev",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -30),
				UpdatedAt:   now.AddDate(0, 0, -1),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -1),
			},
		},
		{
			ID:     "issue:2",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add keyboard navigation",
				"description": "Implement hjkl vim-style navigation for graph exploration",
				"status":      "todo",
				"priority":    2,
				"labels":      []string{"enhancement", "navigation", "p1"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -25),
				UpdatedAt:   now.AddDate(0, 0, -2),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -2),
			},
		},
		{
			ID:     "issue:3",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Implement SQLite persistence",
				"description": "Add SQLite backend for graph storage",
				"status":      "done",
				"priority":    1,
				"labels":      []string{"database", "backend", "p0"},
				"assignee":    "dev",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -40),
				UpdatedAt:   now.AddDate(0, 0, -10),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -10),
			},
		},
		{
			ID:     "issue:4",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Create detail pane component",
				"description": "Display node details when selected in graph",
				"status":      "todo",
				"priority":    2,
				"labels":      []string{"ui", "component"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -20),
				UpdatedAt:   now.AddDate(0, 0, -3),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -3),
			},
		},
		{
			ID:     "issue:5",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add GitHub integration",
				"description": "Fetch issues and PRs from GitHub API",
				"status":      "todo",
				"priority":    3,
				"labels":      []string{"integration", "api", "p2"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -18),
				UpdatedAt:   now.AddDate(0, 0, -4),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -4),
			},
		},
		{
			ID:     "issue:6",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Implement search functionality",
				"description": "Full-text search across nodes",
				"status":      "todo",
				"priority":    3,
				"labels":      []string{"search", "feature", "p2"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -15),
				UpdatedAt:   now.AddDate(0, 0, -5),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -5),
			},
		},
		{
			ID:     "issue:7",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add Linear integration",
				"description": "Sync issues from Linear workspace",
				"status":      "todo",
				"priority":    3,
				"labels":      []string{"integration", "api", "p3"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -12),
				UpdatedAt:   now.AddDate(0, 0, -6),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -6),
			},
		},
		{
			ID:     "issue:8",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Create CLI commands",
				"description": "Add graph manipulation commands",
				"status":      "in_progress",
				"priority":    2,
				"labels":      []string{"cli", "tooling"},
				"assignee":    "dev",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -10),
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "issue:9",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add color themes",
				"description": "Support light and dark mode",
				"status":      "todo",
				"priority":    4,
				"labels":      []string{"ui", "theme", "p3"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -8),
				UpdatedAt:   now.AddDate(0, 0, -1),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -1),
			},
		},
		{
			ID:     "issue:10",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Implement graph filtering",
				"description": "Filter nodes by type, status, labels",
				"status":      "todo",
				"priority":    3,
				"labels":      []string{"feature", "filtering"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -7),
				UpdatedAt:   now.AddDate(0, 0, -2),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -2),
			},
		},
		{
			ID:     "issue:11",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add export functionality",
				"description": "Export graph to JSON, GraphML, DOT formats",
				"status":      "todo",
				"priority":    4,
				"labels":      []string{"export", "feature", "p3"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -6),
				UpdatedAt:   now.AddDate(0, 0, -3),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -3),
			},
		},
		{
			ID:     "issue:12",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Create unit tests",
				"description": "Add test coverage for core modules",
				"status":      "in_progress",
				"priority":    2,
				"labels":      []string{"testing", "quality"},
				"assignee":    "qa",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -5),
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "issue:13",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add documentation",
				"description": "Write user guide and API documentation",
				"status":      "todo",
				"priority":    3,
				"labels":      []string{"documentation", "p2"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -4),
				UpdatedAt:   now.AddDate(0, 0, -1),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -1),
			},
		},
		{
			ID:     "issue:14",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Implement undo/redo",
				"description": "Add command history for graph edits",
				"status":      "todo",
				"priority":    4,
				"labels":      []string{"feature", "ux"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -3),
				UpdatedAt:   now.AddDate(0, 0, -2),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -2),
			},
		},
		{
			ID:     "issue:15",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add performance metrics",
				"description": "Track graph traversal performance",
				"status":      "todo",
				"priority":    3,
				"labels":      []string{"performance", "monitoring"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -2),
				UpdatedAt:   now.AddDate(0, 0, -1),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -1),
			},
		},
		{
			ID:     "issue:16",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Create plugin system",
				"description": "Allow custom node types and visualizations",
				"status":      "todo",
				"priority":    4,
				"labels":      []string{"architecture", "extensibility", "p3"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -1),
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now,
			},
		},
		{
			ID:     "issue:17",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add collaboration features",
				"description": "Multi-user editing and conflict resolution",
				"status":      "todo",
				"priority":    4,
				"labels":      []string{"collaboration", "p3"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now,
			},
		},
		{
			ID:     "issue:18",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Implement graph layout algorithms",
				"description": "Support multiple layout strategies (tree, force-directed, circular)",
				"status":      "in_progress",
				"priority":    2,
				"labels":      []string{"algorithm", "visualization"},
				"assignee":    "dev",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -35),
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now,
			},
		},
		{
			ID:     "issue:19",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add zoom and pan controls",
				"description": "Navigate large graphs efficiently",
				"status":      "todo",
				"priority":    2,
				"labels":      []string{"ui", "navigation", "p1"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -22),
				UpdatedAt:   now.AddDate(0, 0, -3),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -3),
			},
		},
		{
			ID:     "issue:20",
			Type:   graph.NodeTypeIssue,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Implement graph diff tool",
				"description": "Compare graph states over time",
				"status":      "todo",
				"priority":    4,
				"labels":      []string{"tooling", "diff", "p3"},
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -14),
				UpdatedAt:   now.AddDate(0, 0, -5),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -5),
			},
		},

		// PRs (15) - some merged, some open
		{
			ID:     "pr:101",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add SQLite backend implementation",
				"description": "Implements #3 with complete CRUD operations and tests",
				"status":      "merged",
				"number":      101,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/101",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -11),
				UpdatedAt:   now.AddDate(0, 0, -10),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -10),
			},
		},
		{
			ID:     "pr:102",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "WIP: Graph rendering engine",
				"description": "Implements #1 with hierarchical tree layout (in progress)",
				"status":      "open",
				"number":      102,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/102",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -2),
				UpdatedAt:   now.AddDate(0, 0, -1),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -1),
			},
		},
		{
			ID:     "pr:103",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add CLI commands module",
				"description": "Implements #8 with graph manipulation commands",
				"status":      "open",
				"number":      103,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/103",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -1),
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "pr:104",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add unit tests for graph store",
				"description": "Part of #12 - tests for SQLite backend",
				"status":      "open",
				"number":      104,
				"author":      "qa",
				"url":         "https://github.com/example/maat/pull/104",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "pr:105",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add layout algorithm framework",
				"description": "Implements #18 with pluggable layout system",
				"status":      "open",
				"number":      105,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/105",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -1),
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now,
			},
		},
		{
			ID:     "pr:106",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Fix schema validation",
				"description": "Bugfix for node type validation",
				"status":      "merged",
				"number":      106,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/106",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -15),
				UpdatedAt:   now.AddDate(0, 0, -14),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -14),
			},
		},
		{
			ID:     "pr:107",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Refactor TUI model",
				"description": "Clean up state management following Elm Architecture",
				"status":      "merged",
				"number":      107,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/107",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -20),
				UpdatedAt:   now.AddDate(0, 0, -19),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -19),
			},
		},
		{
			ID:     "pr:108",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add documentation for Store interface",
				"description": "Part of #13 - document graph storage API",
				"status":      "merged",
				"number":      108,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/108",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -3),
				UpdatedAt:   now.AddDate(0, 0, -2),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -2),
			},
		},
		{
			ID:     "pr:109",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Performance improvements for graph queries",
				"description": "Optimizes neighbor queries with better indexing",
				"status":      "merged",
				"number":      109,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/109",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -8),
				UpdatedAt:   now.AddDate(0, 0, -7),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -7),
			},
		},
		{
			ID:     "pr:110",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add edge type validation",
				"description": "Enforce valid edge relations in schema",
				"status":      "open",
				"number":      110,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/110",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "pr:111",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Implement GitHub API client",
				"description": "Part of #5 - fetch issues and PRs from GitHub",
				"status":      "draft",
				"number":      111,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/111",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -2),
				UpdatedAt:   now.AddDate(0, 0, -1),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -1),
			},
		},
		{
			ID:     "pr:112",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add theme system",
				"description": "Implements #9 with light and dark themes",
				"status":      "draft",
				"number":      112,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/112",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -1),
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now,
			},
		},
		{
			ID:     "pr:113",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add filtering UI",
				"description": "Implements #10 with filter controls in sidebar",
				"status":      "draft",
				"number":      113,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/113",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "pr:114",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add export commands",
				"description": "Implements #11 with JSON, GraphML, DOT exporters",
				"status":      "draft",
				"number":      114,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/114",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now,
			},
		},
		{
			ID:     "pr:115",
			Type:   graph.NodeTypePR,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"title":       "Add performance monitoring",
				"description": "Implements #15 with metrics collection",
				"status":      "draft",
				"number":      115,
				"author":      "dev",
				"url":         "https://github.com/example/maat/pull/115",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},

		// Commits (30) - with issue references in messages
		{
			ID:     "commit:abc123",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: implement SQLite store (#3)",
				"author":  "dev",
				"hash":    "abc123def456",
				"date":    now.AddDate(0, 0, -11).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -11),
				UpdatedAt:   now.AddDate(0, 0, -11),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -11),
			},
		},
		{
			ID:     "commit:def456",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "fix: add node type validation",
				"author":  "dev",
				"hash":    "def456789abc",
				"date":    now.AddDate(0, 0, -15).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -15),
				UpdatedAt:   now.AddDate(0, 0, -15),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -15),
			},
		},
		{
			ID:     "commit:ghi789",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "refactor: clean up TUI state management",
				"author":  "dev",
				"hash":    "ghi789012jkl",
				"date":    now.AddDate(0, 0, -20).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -20),
				UpdatedAt:   now.AddDate(0, 0, -20),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -20),
			},
		},
		{
			ID:     "commit:jkl012",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "docs: document Store interface (#13)",
				"author":  "dev",
				"hash":    "jkl012345mno",
				"date":    now.AddDate(0, 0, -3).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -3),
				UpdatedAt:   now.AddDate(0, 0, -3),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -3),
			},
		},
		{
			ID:     "commit:mno345",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "perf: optimize neighbor queries",
				"author":  "dev",
				"hash":    "mno345678pqr",
				"date":    now.AddDate(0, 0, -8).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -8),
				UpdatedAt:   now.AddDate(0, 0, -8),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -8),
			},
		},
		{
			ID:     "commit:pqr678",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: add hierarchical tree layout (#1)",
				"author":  "dev",
				"hash":    "pqr678901stu",
				"date":    now.AddDate(0, 0, -2).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -2),
				UpdatedAt:   now.AddDate(0, 0, -2),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -2),
			},
		},
		{
			ID:     "commit:stu901",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: add CLI commands module (#8)",
				"author":  "dev",
				"hash":    "stu901234vwx",
				"date":    now.AddDate(0, 0, -1).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -1),
				UpdatedAt:   now.AddDate(0, 0, -1),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -1),
			},
		},
		{
			ID:     "commit:vwx234",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "test: add unit tests for graph store (#12)",
				"author":  "qa",
				"hash":    "vwx234567yza",
				"date":    now.Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "commit:yza567",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: add pluggable layout system (#18)",
				"author":  "dev",
				"hash":    "yza567890bcd",
				"date":    now.AddDate(0, 0, -1).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -1),
				UpdatedAt:   now.AddDate(0, 0, -1),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -1),
			},
		},
		{
			ID:     "commit:bcd890",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: add edge type validation",
				"author":  "dev",
				"hash":    "bcd890123efg",
				"date":    now.Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		// Additional commits for variety
		{
			ID:     "commit:efg123",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "chore: update dependencies",
				"author":  "dev",
				"hash":    "efg123456hij",
				"date":    now.AddDate(0, 0, -5).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -5),
				UpdatedAt:   now.AddDate(0, 0, -5),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -5),
			},
		},
		{
			ID:     "commit:hij456",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "fix: handle nil metadata gracefully",
				"author":  "dev",
				"hash":    "hij456789klm",
				"date":    now.AddDate(0, 0, -12).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -12),
				UpdatedAt:   now.AddDate(0, 0, -12),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -12),
			},
		},
		{
			ID:     "commit:klm789",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "style: format code with gofmt",
				"author":  "dev",
				"hash":    "klm789012nop",
				"date":    now.AddDate(0, 0, -6).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -6),
				UpdatedAt:   now.AddDate(0, 0, -6),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -6),
			},
		},
		{
			ID:     "commit:nop012",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: add detail pane rendering",
				"author":  "dev",
				"hash":    "nop012345qrs",
				"date":    now.AddDate(0, 0, -4).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -4),
				UpdatedAt:   now.AddDate(0, 0, -4),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -4),
			},
		},
		{
			ID:     "commit:qrs345",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "test: add edge validation tests",
				"author":  "qa",
				"hash":    "qrs345678tuv",
				"date":    now.Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "commit:tuv678",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "docs: add README examples",
				"author":  "dev",
				"hash":    "tuv678901wxy",
				"date":    now.AddDate(0, 0, -9).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -9),
				UpdatedAt:   now.AddDate(0, 0, -9),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -9),
			},
		},
		{
			ID:     "commit:wxy901",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: implement keyboard shortcuts",
				"author":  "dev",
				"hash":    "wxy901234zab",
				"date":    now.AddDate(0, 0, -3).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -3),
				UpdatedAt:   now.AddDate(0, 0, -3),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -3),
			},
		},
		{
			ID:     "commit:zab234",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "refactor: extract layout algorithms",
				"author":  "dev",
				"hash":    "zab234567cde",
				"date":    now.AddDate(0, 0, -7).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -7),
				UpdatedAt:   now.AddDate(0, 0, -7),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -7),
			},
		},
		{
			ID:     "commit:cde567",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "ci: add GitHub Actions workflow",
				"author":  "dev",
				"hash":    "cde567890fgh",
				"date":    now.AddDate(0, 0, -16).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -16),
				UpdatedAt:   now.AddDate(0, 0, -16),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -16),
			},
		},
		{
			ID:     "commit:fgh890",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: add search functionality (#6)",
				"author":  "dev",
				"hash":    "fgh890123ijk",
				"date":    now.AddDate(0, 0, -10).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -10),
				UpdatedAt:   now.AddDate(0, 0, -10),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -10),
			},
		},
		{
			ID:     "commit:ijk123",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: add filter UI controls (#10)",
				"author":  "dev",
				"hash":    "ijk123456lmn",
				"date":    now.Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "commit:lmn456",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: add export functionality (#11)",
				"author":  "dev",
				"hash":    "lmn456789opq",
				"date":    now.Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now,
			},
		},
		{
			ID:     "commit:opq789",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: add theme system (#9)",
				"author":  "dev",
				"hash":    "opq789012rst",
				"date":    now.AddDate(0, 0, -1).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -1),
				UpdatedAt:   now.AddDate(0, 0, -1),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -1),
			},
		},
		{
			ID:     "commit:rst012",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: add GitHub API client (#5)",
				"author":  "dev",
				"hash":    "rst012345uvw",
				"date":    now.AddDate(0, 0, -2).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -2),
				UpdatedAt:   now.AddDate(0, 0, -2),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -2),
			},
		},
		{
			ID:     "commit:uvw345",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: add performance metrics (#15)",
				"author":  "dev",
				"hash":    "uvw345678xyz",
				"date":    now.Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "commit:xyz678",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "feat: add zoom and pan controls (#19)",
				"author":  "dev",
				"hash":    "xyz678901abc",
				"date":    now.AddDate(0, 0, -3).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -3),
				UpdatedAt:   now.AddDate(0, 0, -3),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -3),
			},
		},
		{
			ID:     "commit:abc901",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "docs: document keyboard navigation",
				"author":  "dev",
				"hash":    "abc901234def",
				"date":    now.AddDate(0, 0, -4).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -4),
				UpdatedAt:   now.AddDate(0, 0, -4),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -4),
			},
		},
		{
			ID:     "commit:def234",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "test: add integration tests",
				"author":  "qa",
				"hash":    "def234567ghi",
				"date":    now.Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "commit:ghi567",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "chore: update go.mod and go.sum",
				"author":  "dev",
				"hash":    "ghi567890jkl",
				"date":    now.AddDate(0, 0, -2).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -2),
				UpdatedAt:   now.AddDate(0, 0, -2),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -2),
			},
		},
		{
			ID:     "commit:jkl890",
			Type:   graph.NodeTypeCommit,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"message": "fix: resolve race condition in graph updates",
				"author":  "dev",
				"hash":    "jkl890123mno",
				"date":    now.AddDate(0, 0, -5).Format("2006-01-02"),
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -5),
				UpdatedAt:   now.AddDate(0, 0, -5),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -5),
			},
		},

		// Files (25) - code files modified by PRs
		{
			ID:     "file:1",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/graph/store.go",
				"language": "Go",
				"lines":    479,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -40),
				UpdatedAt:   now.AddDate(0, 0, -11),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -11),
			},
		},
		{
			ID:     "file:2",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/graph/schema.go",
				"language": "Go",
				"lines":    170,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -45),
				UpdatedAt:   now.AddDate(0, 0, -15),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -15),
			},
		},
		{
			ID:     "file:3",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/tui/model.go",
				"language": "Go",
				"lines":    258,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -50),
				UpdatedAt:   now.AddDate(0, 0, -20),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -20),
			},
		},
		{
			ID:     "file:4",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/tui/view.go",
				"language": "Go",
				"lines":    392,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -48),
				UpdatedAt:   now.AddDate(0, 0, -2),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -2),
			},
		},
		{
			ID:     "file:5",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/tui/update.go",
				"language": "Go",
				"lines":    156,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -48),
				UpdatedAt:   now.AddDate(0, 0, -3),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -3),
			},
		},
		{
			ID:     "file:6",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "cmd/maat/main.go",
				"language": "Go",
				"lines":    87,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -60),
				UpdatedAt:   now.AddDate(0, 0, -25),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -25),
			},
		},
		{
			ID:     "file:7",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/cli/commands.go",
				"language": "Go",
				"lines":    234,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -1),
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "file:8",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/layout/tree.go",
				"language": "Go",
				"lines":    312,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -2),
				UpdatedAt:   now.AddDate(0, 0, -1),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -1),
			},
		},
		{
			ID:     "file:9",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/layout/algorithm.go",
				"language": "Go",
				"lines":    189,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -1),
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now,
			},
		},
		{
			ID:     "file:10",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/graph/store_test.go",
				"language": "Go",
				"lines":    456,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "file:11",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/tui/types.go",
				"language": "Go",
				"lines":    152,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -40),
				UpdatedAt:   now.AddDate(0, 0, -20),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -20),
			},
		},
		{
			ID:     "file:12",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/api/github.go",
				"language": "Go",
				"lines":    278,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -2),
				UpdatedAt:   now.AddDate(0, 0, -1),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -1),
			},
		},
		{
			ID:     "file:13",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/theme/colors.go",
				"language": "Go",
				"lines":    145,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -1),
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now,
			},
		},
		{
			ID:     "file:14",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/filter/filter.go",
				"language": "Go",
				"lines":    198,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "file:15",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/export/json.go",
				"language": "Go",
				"lines":    134,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now,
			},
		},
		{
			ID:     "file:16",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/export/graphml.go",
				"language": "Go",
				"lines":    167,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now,
			},
		},
		{
			ID:     "file:17",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/metrics/perf.go",
				"language": "Go",
				"lines":    223,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now,
				UpdatedAt:   now,
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now,
			},
		},
		{
			ID:     "file:18",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "README.md",
				"language": "Markdown",
				"lines":    89,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, -3, 0),
				UpdatedAt:   now.AddDate(0, 0, -9),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -9),
			},
		},
		{
			ID:     "file:19",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "docs/CONSTITUTION.md",
				"language": "Markdown",
				"lines":    326,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, -2, 0),
				UpdatedAt:   now.AddDate(0, 0, -10),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -10),
			},
		},
		{
			ID:     "file:20",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "go.mod",
				"language": "Go Module",
				"lines":    34,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, -3, 0),
				UpdatedAt:   now.AddDate(0, 0, -2),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -2),
			},
		},
		{
			ID:     "file:21",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "Makefile",
				"language": "Make",
				"lines":    45,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, -3, 0),
				UpdatedAt:   now.AddDate(0, -1, 0),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, -1, 0),
			},
		},
		{
			ID:     "file:22",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     ".github/workflows/ci.yml",
				"language": "YAML",
				"lines":    67,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -16),
				UpdatedAt:   now.AddDate(0, 0, -16),
				CreatedBy:   "user",
				AccessLevel: graph.RoleIC,
				SyncedAt:    now.AddDate(0, 0, -16),
			},
		},
		{
			ID:     "file:23",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/tui/keyboard.go",
				"language": "Go",
				"lines":    178,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -3),
				UpdatedAt:   now.AddDate(0, 0, -3),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -3),
			},
		},
		{
			ID:     "file:24",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/tui/render.go",
				"language": "Go",
				"lines":    289,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -2),
				UpdatedAt:   now.AddDate(0, 0, -1),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -1),
			},
		},
		{
			ID:     "file:25",
			Type:   graph.NodeTypeFile,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"path":     "internal/search/search.go",
				"language": "Go",
				"lines":    201,
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, 0, -10),
				UpdatedAt:   now.AddDate(0, 0, -10),
				CreatedBy:   "user",
				AccessLevel: graph.RoleLead,
				SyncedAt:    now.AddDate(0, 0, -10),
			},
		},

		// Services (as mentioned in schema but not yet created)
		{
			ID:     "service:github",
			Type:   graph.NodeTypeService,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"name": "GitHub",
				"type": "api",
				"repo": "github.com/example/maat",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, -3, 0),
				UpdatedAt:   now.AddDate(0, 0, -2),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -2),
			},
		},
		{
			ID:     "service:linear",
			Type:   graph.NodeTypeService,
			Source: "mock",
			Data:   mustJSON(map[string]interface{}{
				"name": "Linear",
				"type": "api",
				"repo": "linear.app/maat",
			}),
			Metadata: graph.NodeMetadata{
				CreatedAt:   now.AddDate(0, -2, 0),
				UpdatedAt:   now.AddDate(0, 0, -6),
				CreatedBy:   "user",
				AccessLevel: graph.RoleExec,
				SyncedAt:    now.AddDate(0, 0, -6),
			},
		},
	}

	// Create edges with realistic relationships
	edges := []graph.Edge{
		// Project owns issues
		{ID: "edge:1", FromID: "project:maat", ToID: "issue:1", Relation: graph.EdgeOwns, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -30)}},
		{ID: "edge:2", FromID: "project:maat", ToID: "issue:2", Relation: graph.EdgeOwns, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -25)}},
		{ID: "edge:3", FromID: "project:backend", ToID: "issue:3", Relation: graph.EdgeOwns, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -40)}},
		{ID: "edge:4", FromID: "project:frontend", ToID: "issue:4", Relation: graph.EdgeOwns, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -20)}},
		{ID: "edge:5", FromID: "project:backend", ToID: "issue:5", Relation: graph.EdgeOwns, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -18)}},

		// Issue blocks issue (dependency relationships)
		{ID: "edge:6", FromID: "issue:2", ToID: "issue:1", Relation: graph.EdgeBlocks, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -25)}},
		{ID: "edge:7", FromID: "issue:4", ToID: "issue:1", Relation: graph.EdgeBlocks, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -20)}},
		{ID: "edge:8", FromID: "issue:8", ToID: "issue:3", Relation: graph.EdgeBlocks, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -10)}},
		{ID: "edge:9", FromID: "issue:18", ToID: "issue:1", Relation: graph.EdgeBlocks, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -30)}},
		{ID: "edge:10", FromID: "issue:19", ToID: "issue:1", Relation: graph.EdgeBlocks, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -22)}},

		// Issue related to issue
		{ID: "edge:11", FromID: "issue:2", ToID: "issue:19", Relation: graph.EdgeRelated, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -22)}},
		{ID: "edge:12", FromID: "issue:6", ToID: "issue:10", Relation: graph.EdgeRelated, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -15)}},
		{ID: "edge:13", FromID: "issue:9", ToID: "issue:4", Relation: graph.EdgeRelated, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -8)}},
		{ID: "edge:14", FromID: "issue:11", ToID: "issue:6", Relation: graph.EdgeRelated, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -6)}},
		{ID: "edge:15", FromID: "issue:16", ToID: "issue:18", Relation: graph.EdgeRelated, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -1)}},

		// PR implements issue
		{ID: "edge:16", FromID: "pr:101", ToID: "issue:3", Relation: graph.EdgeImplements, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -11)}},
		{ID: "edge:17", FromID: "pr:102", ToID: "issue:1", Relation: graph.EdgeImplements, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -2)}},
		{ID: "edge:18", FromID: "pr:103", ToID: "issue:8", Relation: graph.EdgeImplements, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -1)}},
		{ID: "edge:19", FromID: "pr:104", ToID: "issue:12", Relation: graph.EdgeImplements, Metadata: graph.EdgeMetadata{CreatedAt: now}},
		{ID: "edge:20", FromID: "pr:105", ToID: "issue:18", Relation: graph.EdgeImplements, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -1)}},
		{ID: "edge:21", FromID: "pr:111", ToID: "issue:5", Relation: graph.EdgeImplements, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -2)}},
		{ID: "edge:22", FromID: "pr:112", ToID: "issue:9", Relation: graph.EdgeImplements, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -1)}},
		{ID: "edge:23", FromID: "pr:113", ToID: "issue:10", Relation: graph.EdgeImplements, Metadata: graph.EdgeMetadata{CreatedAt: now}},
		{ID: "edge:24", FromID: "pr:114", ToID: "issue:11", Relation: graph.EdgeImplements, Metadata: graph.EdgeMetadata{CreatedAt: now}},
		{ID: "edge:25", FromID: "pr:115", ToID: "issue:15", Relation: graph.EdgeImplements, Metadata: graph.EdgeMetadata{CreatedAt: now}},

		// PR modifies file
		{ID: "edge:26", FromID: "pr:101", ToID: "file:1", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -11)}},
		{ID: "edge:27", FromID: "pr:101", ToID: "file:10", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -11)}},
		{ID: "edge:28", FromID: "pr:102", ToID: "file:4", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -2)}},
		{ID: "edge:29", FromID: "pr:102", ToID: "file:8", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -2)}},
		{ID: "edge:30", FromID: "pr:103", ToID: "file:7", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -1)}},
		{ID: "edge:31", FromID: "pr:104", ToID: "file:10", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now}},
		{ID: "edge:32", FromID: "pr:105", ToID: "file:9", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -1)}},
		{ID: "edge:33", FromID: "pr:106", ToID: "file:2", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -15)}},
		{ID: "edge:34", FromID: "pr:107", ToID: "file:3", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -20)}},
		{ID: "edge:35", FromID: "pr:108", ToID: "file:1", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -3)}},
		{ID: "edge:36", FromID: "pr:109", ToID: "file:1", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -8)}},
		{ID: "edge:37", FromID: "pr:110", ToID: "file:2", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now}},
		{ID: "edge:38", FromID: "pr:111", ToID: "file:12", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -2)}},
		{ID: "edge:39", FromID: "pr:112", ToID: "file:13", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -1)}},
		{ID: "edge:40", FromID: "pr:113", ToID: "file:14", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now}},
		{ID: "edge:41", FromID: "pr:114", ToID: "file:15", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now}},
		{ID: "edge:42", FromID: "pr:114", ToID: "file:16", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now}},
		{ID: "edge:43", FromID: "pr:115", ToID: "file:17", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now}},

		// Commit mentions issue
		{ID: "edge:44", FromID: "commit:abc123", ToID: "issue:3", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -11)}},
		{ID: "edge:45", FromID: "commit:jkl012", ToID: "issue:13", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -3)}},
		{ID: "edge:46", FromID: "commit:pqr678", ToID: "issue:1", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -2)}},
		{ID: "edge:47", FromID: "commit:stu901", ToID: "issue:8", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -1)}},
		{ID: "edge:48", FromID: "commit:vwx234", ToID: "issue:12", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now}},
		{ID: "edge:49", FromID: "commit:yza567", ToID: "issue:18", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -1)}},
		{ID: "edge:50", FromID: "commit:fgh890", ToID: "issue:6", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -10)}},
		{ID: "edge:51", FromID: "commit:ijk123", ToID: "issue:10", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now}},
		{ID: "edge:52", FromID: "commit:lmn456", ToID: "issue:11", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now}},
		{ID: "edge:53", FromID: "commit:opq789", ToID: "issue:9", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -1)}},
		{ID: "edge:54", FromID: "commit:rst012", ToID: "issue:5", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -2)}},
		{ID: "edge:55", FromID: "commit:uvw345", ToID: "issue:15", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now}},
		{ID: "edge:56", FromID: "commit:xyz678", ToID: "issue:19", Relation: graph.EdgeMentions, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -3)}},

		// Service connections
		{ID: "edge:57", FromID: "service:github", ToID: "project:maat", Relation: graph.EdgeOwns, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, -3, 0)}},
		{ID: "edge:58", FromID: "service:linear", ToID: "project:maat", Relation: graph.EdgeOwns, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, -2, 0)}},

		// Additional file relationships
		{ID: "edge:59", FromID: "commit:abc123", ToID: "file:1", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -11)}},
		{ID: "edge:60", FromID: "commit:def456", ToID: "file:2", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -15)}},
		{ID: "edge:61", FromID: "commit:ghi789", ToID: "file:3", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -20)}},
		{ID: "edge:62", FromID: "commit:pqr678", ToID: "file:4", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -2)}},
		{ID: "edge:63", FromID: "commit:nop012", ToID: "file:4", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -4)}},
		{ID: "edge:64", FromID: "commit:wxy901", ToID: "file:23", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -3)}},
		{ID: "edge:65", FromID: "commit:zab234", ToID: "file:8", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -7)}},
		{ID: "edge:66", FromID: "commit:zab234", ToID: "file:9", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -7)}},
		{ID: "edge:67", FromID: "commit:cde567", ToID: "file:22", Relation: graph.EdgeModifies, Metadata: graph.EdgeMetadata{CreatedAt: now.AddDate(0, 0, -16)}},
	}

	return nodes, edges
}

// mustJSON is a helper function for creating JSON from maps.
// Panics if marshaling fails (acceptable for mock data).
func mustJSON(v interface{}) json.RawMessage {
	data, err := json.Marshal(v)
	if err != nil {
		panic(fmt.Sprintf("failed to marshal JSON: %v", err))
	}
	return data
}
